Repository 4GeeksAcademy/spain54-g1-landing-page-with-react, pull requests merged in 2023-12, with the labels that each got.

#11 Feat: Cards
  .vscode/settings.json
  src/js/component/Cards.jsx
  src/js/component/home.jsx
Labels: enhancement

#8 feat: footer.jsx
  src/js/component/Footer.jsx
Labels: enhancement

#10 feat: NavBar.jsx
  src/js/component/NavBar.jsx
Labels: enhancement

#6 feat: Jumbotron
  src/js/component/Jumbotron.jsx
Labels: enhancement

#7 feat: Home
  src/js/component/home.jsx
Labels: enhancement

#12 Fix: Footer
  src/js/component/Footer.jsx
Labels: bug

#13 Fix: Cards container
  src/js/component/Cards.jsx
Labels: bug

#14 Fix: home & jumbotron
  src/js/component/Jumbotron.jsx
  src/js/component/home.jsx
Labels: bug, enhancement

#18 Fix: home & Jumbotron
  src/js/component/Jumbotron.jsx
  src/js/component/home.jsx
Labels: bug, enhancement

#22 Fix: footer-patch-2
  src/js/component/Footer.jsx
Labels: bug

#23 Landing Page con React v1.0 - Listo para entregar
  .vscode/settings.json
  src/js/component/Cards.jsx
  src/js/component/Footer.jsx
  src/js/component/Jumbotron.jsx
  src/js/component/NavBar.jsx
  src/js/component/home.jsx
Labels: enhancement
